---
title: "Prétraitement des Lectures de Séquences"
toc: true
number-sections: true
number-depth: 3
---

Pour pratiquer le contrôle de qualité et le prétraitement des données NGS brutes, nous utiliserons de petits ensembles de données. Les outils sont disponibles sur Galaxy, une plateforme pour l'analyse des données omiques.

Première étape : connectez-vous sur https://usegalaxy.fr

Ensuite, pour vous assurer que vous avez suffisamment de ressources, allez à l'URL :

https://usegalaxy.fr/join-training/td1genomics/

Vous pouvez ensuite revenir sur Galaxy.

## Illumina SE

Vous pouvez renommer votre historique (panneau droit).

Le premier ensemble de données concerne une étude métagénomique du microbiome de la cavité buccale d'un serpent. Après extraction et fragmentation de l'ADN de l'échantillon, une partie du gène 16S rRNA a été amplifiée et séquencée (Illumina Single End) afin d'identifier les bactéries présentes. En raison de contraintes de temps, seule une partie des données sera analysée.

### Données brutes : fichier FASTQ

1. Importez le fichier FASTQ depuis le serveur zenodo :

Copiez l'adresse du lien :
https://zenodo.org/record/3977236/files/female_oral2.fastq-4143.gz

Dans Galaxy, utilisez le bouton Importer des données (en haut à gauche) puis Collez/Obtenez des données, collez le lien et lancez (démarrer).

2. Examinez le fichier (icône de l'œil).

Quelles sont les caractéristiques du format FASTQ ?
Étant donné que les scores sont encodés en utilisant le système SANGER/Illumina 1.8+, quelle est la valeur du score pour la plupart des bases au début de la première lecture ? Est-ce satisfaisant ?

### Contrôle de qualité avec FASTQ

Ouvrez la boîte à outils Contrôle de qualité FASTQ (panneau gauche) et choisissez FastQC.

FastQC

Explorez la qualité des lectures avec FastQC (paramètres par défaut). Consultez le site Web de FastQC pour obtenir de l'aide et des exemples d'analyse.

Qualité de la séquence par base : Quelle est la longueur des lectures ? Comment la qualité évolue-t-elle le long des lectures ?
Scores de qualité par séquence : Que peut-on déduire de ce graphique ?
Contenu de séquence par base : Dans le cas du séquençage du génome (sans amplification spécifique), à quoi devrait ressembler ce graphique ? Le résultat obtenu est-il normal dans notre cas ?
Contenu des adaptateurs : Quel adaptateur est détecté ?

### Traitement des lectures avec Trimmomatic

1. Utilisez Trimmomatic (section Contrôle de qualité FASTQ) pour améliorer la qualité des lectures :

Effectuer l'étape IllUMINACLIP initiale ? Oui, sélectionnez Nextera
Élagage par fenêtre glissante (proposé par défaut)
Supprimer les lectures sous une longueur spécifique (MINLEN) : 20
